server:
  port: 8080
  servlet:
    context-path: /api
spring:
  data:
    web:
      pageable:
        default-page-size: 20
        one-indexed-parameters: true
  datasource:
    url: jdbc:mysql://localhost:3306/db_ps?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update